apiVersion: v1
kind: Service
metadata:
  name: etcd-001
  namespace: rejoinable-etcd
  labels:
    type: cluster
    app: etcd
spec:
  ports:
  - name: etcd-db
    port: 2379
    targetPort: 2379
  selector:
    app: etcd